CREATE TABLE IF NOT EXISTS `motoristas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `empresa_id` int(11) NOT NULL,
  `nome` varchar(100) NOT NULL,
  `cnh` varchar(20) NOT NULL,
  `categoria_cnh` varchar(5) NOT NULL,
  `status` varchar(20) DEFAULT 'Ativo',
  `telefone` varchar(20) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `endereco` text DEFAULT NULL,
  `data_nascimento` date DEFAULT NULL,
  `data_contratacao` date DEFAULT NULL,
  `vencimento_cnh` date DEFAULT NULL,
  `veiculo_id` int(11) DEFAULT NULL,
  `contato_emergencia` varchar(100) DEFAULT NULL,
  `cpf` varchar(14) DEFAULT NULL,
  `rg` varchar(20) DEFAULT NULL,
  `exame_medico` date DEFAULT NULL,
  `observacoes` text DEFAULT NULL,
  `avaliacao` decimal(3,2) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `empresa_id` (`empresa_id`),
  KEY `veiculo_id` (`veiculo_id`),
  CONSTRAINT `motoristas_ibfk_1` FOREIGN KEY (`empresa_id`) REFERENCES `empresa_clientes` (`id`) ON DELETE CASCADE,
  CONSTRAINT `motoristas_ibfk_2` FOREIGN KEY (`veiculo_id`) REFERENCES `veiculos` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci; 